### PR TITLE
ecto3

### LINKED ISSUE #26: Todo: Support ecto 3 and ecto_sql
Ecto 3 is coming in the next couple days and with it the recommended upgrade path for those using it for database interaction is to change dependency from ecto to ecto_sql.

I think to support backwards compatibly for presumably a long time we'll want to introduce an optional dependency.

Reference [commit](https://github.com/elixir-ecto/ecto/commit/dc30e1b199dfd698cb28a21d8a1a2578705e5329) and [announcement](http://blog.plataformatec.com.br/2018/10/a-sneak-peek-at-ecto-3-0-breaking-changes/).

I'll be able to take this on eventually as I'm working on a new project that will be using ecto_sql and will want to use this lib, if no one else gets to it before then.

### PR DESCRIPTION
**Pull request by mbuhot**
Resolves #26 

 - Depends on `ecto_sql`
 - Uses `utc_datetime_usec` for compatibility with existing applications
 - Uses explicit `select:` instead of `returning: true` in calls to `Repo.update_all`
 - Credo updated to 1.0 with warnings fixed

### CODE REVIEW

**Comment by VitorTrin** [comment]
How would I make ecto_job use :naive_datetime_usec in the timestamps?

**Comment by mbuhot** [comment]
@VitorTrin does putting `@timestamps_opts` in your module before `use EctoJob.JobQueue` work?

**Comment by VitorTrin** [comment]
> @VitorTrin does putting @timestamps_opts in your module before use EctoJob.JobQueue work?

According to the ecto changelog I should do that and also put  
```
migration_timestamps: [type: :naive_datetime_usec]
```
in my Repo config, and the combination worked for my schemas, but the ecto_job schemas continue to expect truncated timestamps.

**Comment by seangeo** [comment]
Hi @mbuhot just letting you know that we’ve tested this branch with ecto 3 on our app and it worked fine. Thanks. 👍

**Comment by mbuhot** [comment]
Thanks @seangeo, merged!

**Comment by baron** [comment]
@mbuhot Thank you for the update!

**Comment by cpjolicoeur** [comment]
@mbuhot Does this now required all ecto jobs to be scheduled with an `Etc/UTC` time zone instead of any other alternative timezone?  Do we need to schedule jobs in UTC?

**Comment by mbuhot** [comment]
@cpjolicoeur I believe the behaviour for ecto is to normalise to UTC when inserting into a `utc_datetime` column.

So your application code should be fine using any timezone to create the job, but if you query the jobs table directly you’ll get back UTC times.

**Comment by cpjolicoeur** [comment]
@mbuhot When I schedule a job with the `schedule:` option and use a `DateTime` that is in any zone other than `Etc/UTC` the ecto job worker fails because the `utc_datetime_usec` code expects a date in UTC.

For now, I'm manually converting my localized `DateTime` objects into UTC so that I can `schedule:` jobs with them in that manner.

I didn't know if this was expected behavior or not.

**Comment by mbuhot** [comment]
@cpjolicoeur yes it looks like ecto requires a UTC Timezone https://hexdocs.pm/ecto/Ecto.Schema.html#module-the-datetime-types

I was confusing timezones with the support for UTC offsets  (https://github.com/elixir-ecto/ecto/pull/2054)

Should we add something to the docs to clarify?

**Comment by cpjolicoeur** [comment]
@mbuhot Not sure, couldn't hurt I suppose.   Since `ecto_job` is built on top of `ecto` it makes sense that you shouldn't need to explain the underpinnings of how ecto is implemented, but I think it probably couldn't hurt from a user-perspective.  I at first, didnt put 2 and 2 together and think about that fact, and tried inserting something scheduled in a none UTC timezone.
 
So it might help to at least be explicit about it in the docs.

Or maybe, `ecto_job` should just use `DateTime.shift_zone/3` before inserting scheduled jobs to ensure they are always inserted in `Etc/UTC` timezone?

I could probably try to work up a PR for the latter if you need help on it, but not for the next few days most likely.

**Comment by mbuhot** [comment]
@cpjolicoeur `DateTime.shift_zone/3` looks good 👍 

With a note in the docs that a Timezone database should be configured globally as per the DateTime docs if non UTC timezones are required.

**Pull request merged**
